color: null
description: null
fieldLayouts:
  bae2897f-9989-4cb2-83e2-874eeeeaf113:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:48:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 918673e2-c882-44b9-b2ce-b7721c844900 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 974640e9-ebc7-4bf7-b3d8-1b9f40df986b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e117bfa-7150-4043-8c68-718d51de409e
        userCondition: null
handle: blockText
hasTitleField: false
icon: align-left
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
