color: null
description: null
fieldLayouts:
  65c6c5a3-175b-4dae-a351-d0a62957d879:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1fe26970-c003-47c3-a6b9-902f906507d0 # Heading
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d423213f-d62e-4299-90dd-32be1339cc36
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T08:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 848cfe22-21e5-4034-bc6e-d5ba7d045860 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbc08b96-6a2e-43a5-ac30-8e945837b615
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T08:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1fe26970-c003-47c3-a6b9-902f906507d0 # Heading
            handle: signature
            includeInCards: false
            instructions: null
            label: Signature
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c7667d5-05bd-4f67-a89e-c19e695845d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T08:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 848cfe22-21e5-4034-bc6e-d5ba7d045860 # Image
            handle: logos
            includeInCards: false
            instructions: null
            label: Logos
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1edf2260-a297-4083-bd45-4fb29f7bb0ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2591cd25-6244-47f3-99e6-230444041825
        userCondition: null
handle: blockQuote
hasTitleField: false
icon: quote-left
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
