color: null
description: null
fieldLayouts:
  080c24b1-98da-4cb2-b5c1-086a93188fcf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:50:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 848cfe22-21e5-4034-bc6e-d5ba7d045860 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dd382cc-e0cc-442f-be7f-4e2c142e4924
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T08:50:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1fe26970-c003-47c3-a6b9-902f906507d0 # Heading
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b5a77e5-c0e7-4b2c-9dfa-9a07ef18ceb1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c7ca0c2-92a6-495a-984b-ec785aa06d17
        userCondition: null
handle: blockImage
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
