color: null
description: null
fieldLayouts:
  8ee5673c-30fc-4982-87e6-8b1fb9423ac3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-01T09:01:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b73c4968-d3b4-4897-bea9-622b65c963bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-01T09:02:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fa6d84f-bb6c-48b0-9a0a-141f7eba09fe # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d9a85e8-676c-48ed-9f0e-dfcc7d61548b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a3d5d47-1929-471b-af4a-ea9a8bbc5b2d
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
