altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  890d4503-0e3e-48ba-9611-5679799ef580:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-31T14:37:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fc562478-b981-43c4-82ce-19ba1d299436
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f7183c3-a182-476d-a98f-d186fb12443e
        userCondition: null
fs: documents
handle: documents
name: Documents
sortOrder: 3
subpath: documents
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: documents
