altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  48eb6187-f437-4cf0-8a44-4b63f5a0dacd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-31T14:36:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ae476a13-bb35-4d9a-b1ee-aad6c3552735
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e985ccec-bb99-4699-a042-10d3f8e944eb
        userCondition: null
fs: assets
handle: icons
name: Icons
sortOrder: 2
subpath: icons
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: icons
