columnSuffix: null
handle: snippet
instructions: null
name: Snippet
searchable: false
settings:
  availableLanguages:
    - html
  codeFolding: false
  defaultValue: ''
  fontSize: 14
  language: html
  lineNumbers: false
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: false
  singleLineEditor: false
  theme: vs-dark
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
