dateModified: 1754318811
email:
  fromEmail: admin@contentreactor.com
  fromName: 'Content Reactor Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
  documents:
    hasUrls: true
    name: Documents
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/media'
    type: craft\fs\Local
    url: '@web/media'
meta:
  __names__:
    00aa8e14-8807-4b4b-8ce2-97844307f053: Snippet # Snippet
    1d483cb7-a260-4fc2-992f-85c75c9994d2: 'Plain Text' # Plain Text
    1fe26970-c003-47c3-a6b9-902f906507d0: Heading # Heading
    2cc9f560-eb80-4651-a2f9-3e636c7e1346: Code # Code
    2fc4c59f-d552-44f9-8aa2-d76beb745655: Text # Text
    3e568148-3996-4b8b-9b06-5b82564b4dbb: ' Code Snippets' #  Code Snippets
    6a09e376-2aef-4933-b967-742c7bb9b286: 'Two Columns' # Two Columns
    6be6041d-4565-4d7b-bcbd-84b9106268fa: Pages # Pages
    7fa6d84f-bb6c-48b0-9a0a-141f7eba09fe: 'Content Builder' # Content Builder
    9f072c48-2335-4a1a-b9fa-2a1dab401231: Home # Home
    9f8688ef-6452-42cf-a367-115f8dddb9f7: Spacer # Spacer
    11b6c333-1ae8-431d-a2a1-791fb73682b1: 'Image Large Webp' # Image Large Webp
    23c46cf0-788b-493d-bcde-3fc4f4aa9bb3: 'Image Webp' # Image Webp
    24d986c7-fbb1-494b-9b9f-6a63816b8302: 'Body Bottom Snippets' # Body Bottom Snippets
    41ea0f10-7d8d-466b-8b08-a0579c86636f: 'Craft Starter' # Craft Starter
    087df17e-021e-4dce-94fb-c501972eab99: Icons # Icons
    87ed5dd0-ce5d-449b-97e8-2beb9cfc1cd3: 'Image Png - Mobile' # Image Png - Mobile
    94e92663-c307-46ec-9ebe-84f9f05ddb00: 'Text Image' # Text Image
    194a3bd0-3efe-44a5-95b0-1e1add6fefed: 'Image Webp - Mobile' # Image Webp - Mobile
    0375b0c2-b974-4d8e-8ed3-b8212b796ca7: 'Public Schema' # Public Schema
    500e932e-d2f1-4151-a4d1-87959fde38d8: Images # Images
    848cfe22-21e5-4034-bc6e-d5ba7d045860: Image # Image
    3160ca85-7aff-4ce6-a9cf-8fc47ff0f26c: Page # Page
    11284eb7-3a0f-4b0a-9c26-0ff426879b06: English # English
    918673e2-c882-44b9-b2ce-b7721c844900: Text # Text
    a1317ec9-e0ef-408f-a1ce-95d174fa61c3: Home # Home
    ac304521-fdfd-46c1-a193-ebd9b6abf8a1: 'Body Code' # Body Code
    c7e65717-cea4-4e1e-af12-bbd562fbd6d5: 'Head Snippets' # Head Snippets
    cbb78b6e-0a42-4344-9e58-20baf4c74f26: Simple # Simple
    d573e0ec-cce6-412f-8cf9-096fbf20406f: 'Image Large Png' # Image Large Png
    d603b412-0439-4ff0-a6ae-cf6ffbf52513: Quote # Quote
    e43304de-cb3b-4edd-865b-380e672e3f51: 'Image Png' # Image Png
    f03bf07d-6234-40d9-abb4-68a8591d8136: Documents # Documents
    fd4aa143-fc8c-48c6-8681-8d5383670be3: Image # Image
plugins:
  _site-plugin:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Starter'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
